GET https://young-oasis-07913.herokuapp.com/api/v1/flower

###
POST https://young-oasis-07913.herokuapp.com/api/v1/flower
Content-Type: application/json

{
  "sepalLength": 100,
  "color": "BLUE",
  "price": 100
}
